services:
  jaeger:
    image: jaegertracing/jaeger:2.3.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC 接收端口
      - "14268:14268"  # HTTP 接收端口
      - "4319:4317" # OTLP gRPC receiver
      - "4320:4318" # OTLP http receiver
    networks:
      - otel

  zipkin:
    image: openzipkin/zipkin:3.4
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - otel

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.119.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    container_name: otel-collector
    volumes:
      - ./docker/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
    networks:
      - otel

networks:
  otel:
    driver: bridge
