server:
  port: 8080

spring:
  application:
    name: online-shop

management:
  endpoints:
    web:
      exposure:
        include: '*'
  otlp:
    tracing:
      endpoint: http://localhost:4318
  tracing:
    sampling:
      probability: 1.0

